/values:
  get:
    description: Get values
    security:
      - bearer: []
    tags:
      - Values

    responses:
      '200':
        description: OK - Get the list of values
        content: 
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/MyValue'

  post:
    description: Post a value
    security:
      - bearer: []
    tags:
      - Values

    requestBody:
      requred: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MyValue'

    responses:
      '200':
        description: OK - Post success.

  put:
    description: Put a value
    security:
      - bearer: []
    tags:
      - Values
  
    requestBody:
      requred: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MyValue'

    responses:
      '200':
        description: OK - Put success.


/values/{id}:
  get:
    description: Get a value of the id specified
    security:
      - bearer: []
    tags:
      - Values

    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: Id of the value to request.

    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyValue'


/values/clear:
  post:
    description: Clear all values
    security:
      - bearer: []
    tags:
      - Values

    responses:
      '200':
        description: OK - Clear all value success.


components:
  schemas:
    MyValue:
      $ref: '/oas/schemas/my-value.json'