openapi: 3.0.2
info:
  title: Simple API overview
  description: A simple API overview for testing purposes.
  version: 1.0.0
servers:
- url: 'https://{host}
  variables:
    host:
      enum:
        - 'localhost'
        - 'test-qa.com'
      default: 'localhost'
      description: >-
          this value is assigned by the service provider, in this example
          `gigantic-server.com`
paths:
  /:
    get:
      description: Default endpoint
      responses:
        '200':
          description: A list of pets.
