openapi: 3.0.2


info:
  title: DumApi API
  description: Account login and Values management.
  version: 1.0.0


servers:
- url: 'http://localhost:5000'
  description: Development server


paths:
  /api/account:
    post:
      description: Login
      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      
      responses:
        '200':
          description: OK - Get a bearer token.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/AccessToken'

      tags:
        - Account

  /api/values:
    get:
      description: Get values

      security:
        - bearerAuth: []

      responses:
        '200':
          description: OK - Get the list of values
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DumObj'

      tags:
        - Values

    post:
      description: Post a value

      security:
        - bearerAuth: []

      requestBody:
        requred: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DumObj'

      responses:
        '200':
          description: OK - Post success.

      tags:
        - Values

    put:
      description: Put a value
    
      security:
        - bearerAuth: []
    
      requestBody:
        requred: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DumObj'

      responses:
        '200':
          description: OK - Put success.

      tags:
        - Values

  /api/values/{id}:
    get:
      description: Get a value of the id specified

      security:
        - bearerAuth: []

      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Id of the value to request.

      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DumObj'

      tags:
        - Values

  /api/values/clear:
    post:
      description: Clear all values

      security:
        - bearerAuth: []

      responses:
        '200':
          description: OK - Clear all value success.

      tags:
        - Values


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AccessToken:
      type: object
      properties:
        token:
          type: string
    
    Credentials:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
      example:
        username: 'Kimserey'
        password: '123'

    DumObj:
      type: object
      properties:
        id:
          type: string
        value:
          type: number
      required:
        - id
        - value
      example:
        id: 'hello'
        value: 10