openapi: 3.0.2
info:
  title: DumApi API
  version: 1.0.0
servers:
- url: 'http://localhost:5000'
  description: Development server
paths:
  /:
    get:
      description: Default endpoint
      responses:
        '200':
          description: A list of pets.
