openapi: 3.0.2

info:
  title: DumApi API
  description: Account login and Values management.
  version: 1.0.0

servers:
- url: 'http://localhost:5000/api'
  description: Development server

paths:
  /account:
    $ref: '/oas/paths/account.yml#%2Faccount'

  /values:
    $ref: '/oas/paths/values.yml#%2Fvalues'

  /values/{id}:
    $ref: '/oas/paths/values.yml#%2Fvalues%2F%7Bid%7D'

  /values/clear:
    $ref: '/oas/paths/values.yml#%2Fvalues%2Fclear'

components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AccessToken:
      $ref: '/oas/schemas/token.yml#AccessToken'
    
    Credentials:
      $ref: '/oas/schemas/models.yml#Credentials'

    DumObj:
      $ref: '/oas/schemas/models.yml#DumObj'