openapi: 3.0.2

info:
  title: My API
  version: 1.0.0
  
servers:
  - url: 'http://localhost:8080'
    description: >-
      Development server

paths:
  /api/values:
    $ref: '/sampleopenapi/paths/values.yml#%2Fapi%2Fvalues'
  
  /api/values/{id}:
    $ref: '/sampleopenapi/paths/values.yml#%2Fapi%2Fvalues%2F%7Bid%7D'